-- legacy_init.sql
-- Base de Datos: Db_OnPremise (Legacy)

-- 1. Limpieza
DROP TABLE IF EXISTS customers;

-- 2. Creación de la tabla (Inglés - Estructura Legacy)
CREATE TABLE customers (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_name VARCHAR(150) NOT NULL,
    email VARCHAR(100),
    total_balance DECIMAL(15, 2) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 3. Inserción de datos históricos
INSERT INTO customers (business_name, email, total_balance) 
VALUES ('Tech Solutions Ltd.', 'contact@techsolutions.com', 50000.00);

INSERT INTO customers (business_name, email, total_balance) 
VALUES ('Global Imports Inc.', 'admin@globalimports.com', 12500.50);

INSERT INTO customers (business_name, email, total_balance) 
VALUES ('Consulting Group LLC', 'info@consultinggroup.com', 750.00);

-- 4. Ajuste de secuencia
-- Importante: Como insertamos 3 registros manuales, le decimos a Postgres 
-- que el próximo ID autogenerado debe ser el 4.
ALTER TABLE customers ALTER COLUMN id RESTART WITH 4;