-- Recuerda primero crear la base de datos
CREATE DATABASE "Db_OnPremise";

-- Despues de crear la base ejecutar lo siguiente
-- 1. Limpieza
DROP TABLE IF EXISTS customers;

-- 2. Creación de la tabla 
CREATE TABLE customers (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_name VARCHAR(150) NOT NULL,
    email VARCHAR(100),
    total_balance DECIMAL(15, 2) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 3. Inserción de datos 
INSERT INTO customers (business_name, email, total_balance) 
VALUES ('Tech Solutions Ltd.', 'contact@techsolutions.com', 50000.00);

INSERT INTO customers (business_name, email, total_balance) 
VALUES ('Global Imports Inc.', 'admin@globalimports.com', 12500.50);

INSERT INTO customers (business_name, email, total_balance) 
VALUES ('Consulting Group LLC', 'info@consultinggroup.com', 750.00);

-- Verificamos
SELECT * FROM customers;